name: Executing Tests with SHAFT

on:
  push:
    branches: [ "main" ]
  #pull_request:
   # branches: [ "main" ]

jobs:
  SHAFT_Test_Execution:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'zulu'
        cache: maven

    - name: Run Tests
      run: mvn clean test
 
      #Rename the generated allure report file to be index.html
    - name: Rename report to index.html
      if: always()
      run: |
        mv ./allure-report/*_AllureReport.html ./allure-report/index.html
         
    - name: Deploy report to Github Pages #Deploy the generated html report to the 'Github_Pages' in order to be easily accessible
      if: always() 
      #This means regardless of the previous step output, this step will be executed
      uses: peaceiris/actions-gh-pages@v2
      
      env:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }} #The GitHub Actions generated token for the workflow to be able to deploy the output to the GitHubPages
        PUBLISH_BRANCH: gh-pages #The branch at which the report will be published to (needs to be separate branch)
        PUBLISH_DIR: ./allure-report #This is the directory at which the html report was generated